name: Build and upload binary artifact

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and package project
      run: mvn -f pom.xml package
    - name: Show contents of the current working directory
      run: ls -la
    - name: Show contents of a target directory
      run: ls -la target
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ./target/car-properties-service-0.0.1-SNAPSHOT.jar