name: Build, test and deliver container

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Start Mysql for integration test
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'cardb_test' # Optional, default value is "test". The specified database which will be created.
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
      
      - name: Build, test and package project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lodebosmans_apt_car_service
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/apt_car_service:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/apt_car_service:latest
        
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./target/car-properties-service-0.0.1-SNAPSHOT.jar